apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: '/$1'
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /monitoring/loki/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: loki-srv
                port:
                  number: 3100
