apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: debabrata100/ticketing-expiration
          env:
            - name: SERVICE_NAME
              value: expiration
            - name: LOKI_URL
              value: http://loki-srv:3100
            - name: NATS_ClIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_ClSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv
